version: "3.8"
services:
  rabbitmq3:
    container_name: "rabbitmqmsgbroker"
    image: rabbitmq:3.8-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - msgrabbit

networks:
  msgrabbit:
