version: "3"
services:
  dbpostgresql:
    image: "postgres"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: postgresDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      restart: unless-stopped

  app:
    build: .
    image: appuserlogged
    container_name: appuserlogged
    ports:
      - "8084:8080"
    depends_on:
      - dbpostgresql
